### ISSUE TITLE
Failed to activate the minimap package

### ISSUE THREAD

**Issue by stoe** [abe33/minimap-color-highlight#4]
update installed

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [minimap-color-highlight](https://github.com/abe33/minimap-color-highlight) package, v4.1.0

### Stack Trace

Failed to activate the minimap package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:355:117)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Users/stoe/.dotfiles/atom.symlink/packages/minimap-color-highlight/node_modules/atom-utils/lib/atom-utils.js:25:46
  at Array.forEach (native)
  at /Users/stoe/.dotfiles/atom.symlink/packages/minimap-color-highlight/node_modules/atom-utils/lib/atom-utils.js:24:25
  at module.exports.requirePackages (/Users/stoe/.dotfiles/atom.symlink/packages/minimap-color-highlight/node_modules/atom-utils/lib/atom-utils.js:8:14)
  at MinimapColorHighlight.activate (/Users/stoe/.dotfiles/atom.symlink/packages/minimap-color-highlight/lib/minimap-color-highlight.coffee:6:3)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -3:09.8 core:backspace (atom-text-editor.editor)
     -2:25.6 beautify:beautify-editor (atom-text-editor.editor)
     -2:23.7 snippets:previous-tab-stop (atom-text-editor.editor)
     -2:23.7 editor:outdent-selected-rows (atom-text-editor.editor)
     -2:23.5 snippets:previous-tab-stop (atom-text-editor.editor)
     -2:23.5 editor:outdent-selected-rows (atom-text-editor.editor)
     -2:22.2 beautify:beautify-editor (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-pair"
    ],
    "themes": [
      "one-dark-ui",
      "monokai-syntax-for-one-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, vundefined
language-apache, v1.2.0
language-batch, v0.3.2
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-scss-lint, v0.0.14
linter-shellcheck, v0.0.7
minimap, v4.6.0
minimap-color-highlight, v4.1.0
minimap-git-diff, v4.1.2
monokai-syntax-for-one-dark, v0.2.1
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by abe33** [comment]
This is a known issue with the `settings-view`, please see atom/settings-view#416 for more information. The issue should only occurs only after the package update so a restart should fix things.

Closing it to keep things in one place.
